/**
 * configWriter.js
 * Generates bakesail.cfg from a settings object and saves it via Moonraker.
 *
 * Also handles:
 *  - Writing bakesail_wizard.cfg (single [output_pin bakesail_test_pin] block)
 *    for test-pin operations during the wizard
 *  - Patching [include bakesail.cfg] into printer.cfg on first run
 */

// ── Helpers ───────────────────────────────────────────────────────────────────

function hexToKlipperRgb(hex) {
  const r = parseInt(hex.slice(1, 3), 16) / 255
  const g = parseInt(hex.slice(3, 5), 16) / 255
  const b = parseInt(hex.slice(5, 7), 16) / 255
  return { r: r.toFixed(3), g: g.toFixed(3), b: b.toFixed(3) }
}

function sectionHeader(title) {
  const bar = '='.repeat(60)
  return `# ${bar}\n# ${title}\n# ${bar}\n`
}

function comment(text) {
  return `# ${text}`
}

// ── Main generator ────────────────────────────────────────────────────────────

export function generateBakesailCfg(settings) {
  const lines = []

  lines.push(comment('bakesail.cfg — generated by Bakesail'))
  lines.push(comment('Do not edit manually. Use the Settings page to regenerate.'))
  lines.push(comment(`Generated: ${new Date().toISOString()}`))
  lines.push('')

  // ── Thermocouple sensors ─────────────────────────────────────────────────
  // Compute valid TCs (used when embedding sensor in heater_generic)
  // No standalone [temperature_sensor] objects are created for TCs —
  // they are embedded directly in [heater_generic] to avoid the
  // dual-pin-reference Klipper error when the same SPI pins are declared twice.
  const validTcs = settings.thermocouples.filter(
    tc => tc.csPin && tc.sckPin && tc.misoPin
  )

  // ── Heater zones ─────────────────────────────────────────────────────────
  const validZones = settings.zones.filter(z => {
    const pin = _resolveHeaterPin(z, settings)
    return pin && pin !== 'UNSET'
  })
  if (validZones.length > 0) {
    lines.push(sectionHeader('Heater zones'))
    for (const zone of validZones) {
      const heaterPin = _resolveHeaterPin(zone, settings)
      const tcId      = settings.zoneTcMap[zone.id]
      const tc        = validTcs.find(t => t.id === tcId)

      lines.push(`[heater_generic ${_zoneName(zone)}]`)
      lines.push(`heater_pin: ${heaterPin}`)

      if (tc) {
        lines.push(`sensor_type: MAX31855`)
        lines.push(`sensor_pin: ${tc.csPin}`)
        lines.push(`spi_software_sclk_pin: ${tc.sckPin}`)
        lines.push(`spi_software_miso_pin: ${tc.misoPin}`)
        lines.push(`spi_software_mosi_pin: ${tc.mosiPin || tc.misoPin}`)
      } else {
        lines.push(comment('No TC assigned — using host temperature as placeholder'))
        lines.push(`sensor_type: temperature_host`)
      }

      lines.push(`control: pid`)
      lines.push(`pid_kp: 10.0`)
      lines.push(`pid_ki: 0.5`)
      lines.push(`pid_kd: 100.0`)
      lines.push(`min_temp: 0`)
      lines.push(`max_temp: 350`)
      lines.push(`pwm_cycle_time: 0.1`)
      lines.push('')
    }
  }

  // ── Fans ─────────────────────────────────────────────────────────────────
  const validFans = settings.fans.filter(f => f.pin)
  if (validFans.length > 0) {
    lines.push(sectionHeader('Fans'))
    for (const fan of validFans) {
      if (!fan.pin) continue
      if (fan.pwm) {
        lines.push(`[fan_generic ${_fanName(fan)}]`)
        lines.push(`pin: ${fan.pin}`)
      } else {
        lines.push(`[output_pin ${_fanName(fan)}]`)
        lines.push(`pin: ${fan.pin}`)
        lines.push(`value: 0`)
        lines.push(`shutdown_value: 0`)
      }
      lines.push('')
    }
  }

  // ── Vacuum ────────────────────────────────────────────────────────────────
  if (settings.vacuum.pen && settings.vacuum.penPin) {
    lines.push(sectionHeader('Vacuum — manual pen'))
    lines.push(`[output_pin vacuum_pen]`)
    lines.push(`pin: ${settings.vacuum.penPin}`)
    lines.push(`value: 0`)
    lines.push(`shutdown_value: 0`)
    lines.push('')
  }

  if (settings.vacuum.nozzle && settings.vacuum.nozzlePin) {
    lines.push(sectionHeader('Vacuum — nozzle'))
    lines.push(`[output_pin nozzle_vacuum]`)
    lines.push(`pin: ${settings.vacuum.nozzlePin}`)
    lines.push(`value: 0`)
    lines.push(`shutdown_value: 0`)
    lines.push('')
  }

  // ── Illumination ──────────────────────────────────────────────────────────
  if (settings.illumination.laser && settings.illumination.laserPin) {
    lines.push(sectionHeader('Laser / spot illumination'))
    lines.push(`[output_pin laser]`)
    lines.push(`pin: ${settings.illumination.laserPin}`)
    lines.push(`value: 0`)
    lines.push(`shutdown_value: 0`)
    lines.push('')
  }

  if (settings.illumination.neopixel && settings.illumination.neopixelPin) {
    lines.push(sectionHeader('NeoPixel light bar'))
    const { r, g, b } = hexToKlipperRgb(settings.illumination.neopixelColor || '#ffffff')
    lines.push(`[neopixel light_bar]`)
    lines.push(`pin: ${settings.illumination.neopixelPin}`)
    lines.push(`chain_count: ${settings.illumination.neopixelCount || 8}`)
    lines.push(`color_order: GRB`)
    lines.push(`initial_RED: ${r}`)
    lines.push(`initial_GREEN: ${g}`)
    lines.push(`initial_BLUE: ${b}`)
    lines.push('')
  }

  // ── Stepper motion axes ───────────────────────────────────────────────────
  const motionSlots = settings.stepperSlots.filter(s =>
    s.function.startsWith('motion_')
  )
  if (motionSlots.length > 0) {
    lines.push(sectionHeader('Motion axes'))
    for (const slot of motionSlots) {
      const axis = slot.function.replace('motion_', '')
      const mot = settings.motion || {}
      lines.push(`[stepper_${axis}]`)
      lines.push(`step_pin: ${slot.stepPin}`)
      lines.push(`dir_pin: ${slot.dirPin}`)
      lines.push(`enable_pin: !${slot.enablePin}`)
      lines.push(`microsteps: ${mot.microsteps || 16}`)
      lines.push(`rotation_distance: ${mot.rotationDistance || 8}`)
      lines.push(`endstop_pin: ${slot.endstopPin || 'probe:z_virtual_endstop'}`)
      lines.push(`position_min: 0`)
      lines.push(`position_max: ${mot[axis + 'Max'] || 50}`)
      if (axis === 'z') lines.push(`homing_speed: 5`)
      lines.push('')
    }
  }

  // ── Test pin placeholder (updated dynamically during wizard) ─────────────
  lines.push(sectionHeader('Wizard test pin — updated during setup'))
  lines.push(comment('This pin is temporarily reconfigured during the setup wizard'))
  lines.push(comment('to allow hardware testing. Safe to ignore after setup.'))
  lines.push(`[output_pin bakesail_test_pin]`)
  lines.push(`pin: ${_firstAvailablePin(settings)}`)
  lines.push(`value: 0`)
  lines.push('')

  // ── Main [bakesail] block ─────────────────────────────────────────────────
  lines.push(sectionHeader('Bakesail main configuration'))
  lines.push(`[bakesail]`)
  lines.push(`device_type: ${settings.deviceType}`)
  lines.push(`machine_class: ${settings.machineClass}`)
  lines.push(`profiles_path: ~/printer_data/config/bakesail_profiles`)
  lines.push('')

  // Zones numbered contiguously from 1 regardless of settings store IDs.
  // sensor_zoneN is omitted — bakesail.py reads temperature from the heater directly.
  validZones.forEach((zone, idx) => {
    const n = idx + 1
    lines.push(`heater_zone${n}: heater_generic ${_zoneName(zone)}`)
    if (zone.offset) {
      lines.push(`offset_zone${n}: ${zone.offset}`)
    }
  })
  lines.push('')

  // Fan references — tell bakesail.py which fan objects to report
  for (let i = 0; i < validFans.length; i++) {
    lines.push(`fan${i + 1}: fan_generic ${_fanName(validFans[i])}`)
  }

  // Optional peripherals
  if (settings.vacuum.pen)       lines.push(`has_vacuum_pen: True`)
  if (settings.vacuum.nozzle)    lines.push(`has_nozzle_vacuum: True`)
  if (settings.illumination.laser)    lines.push(`has_laser: True`)
  if (settings.illumination.neopixel) lines.push(`has_neopixel: True`)
  if (settings.cameras.bga)      lines.push(`bga_camera: ${settings.cameras.bga}`)
  if (settings.cameras.alignment)  lines.push(`alignment_camera: ${settings.cameras.alignment}`)
  if (settings.cameras.alignment2) lines.push(`alignment_camera2: ${settings.cameras.alignment2}`)
  lines.push('')

  // ── Macros include ────────────────────────────────────────────────────────
  lines.push(`[include bakesail_macros.cfg]`)
  lines.push('')

  return lines.join('\n')
}

// ── Wizard test pin config ────────────────────────────────────────────────────

export function generateTestPinCfg(pin) {
  return [
    comment('bakesail_wizard.cfg — temporary test pin config'),
    comment('Rewritten by the setup wizard during hardware testing.'),
    '',
    `[output_pin bakesail_test_pin]`,
    `pin: ${pin}`,
    `value: 0`,
    '',
  ].join('\n')
}

// ── Save helpers ──────────────────────────────────────────────────────────────

export async function saveBakesailCfg(settings) {
  const content = generateBakesailCfg(settings)
  return _uploadConfig('bakesail.cfg', content)
}

export async function saveTestPinCfg(pin) {
  const content = generateTestPinCfg(pin)
  return _uploadConfig('bakesail_wizard.cfg', content)
}

async function _uploadConfig(filename, content) {
  const blob = new Blob([content], { type: 'text/plain' })
  const form = new FormData()
  form.append('file', blob, filename)
  form.append('root', 'config')

  const res = await fetch('/server/files/upload', { method: 'POST', body: form })
  if (!res.ok) throw new Error(`Failed to save ${filename}: ${res.status}`)
  return true
}

// ── Patch printer.cfg to include bakesail.cfg ────────────────────────────────

export async function ensurePrinterCfgInclude() {
  try {
    const res = await fetch('/server/files/config/printer.cfg')
    if (!res.ok) throw new Error('Could not read printer.cfg')
    const text = await res.text()

    if (text.includes('[include bakesail.cfg]')) return true  // already there

    const patched = text.trimEnd() + '\n\n[include bakesail.cfg]\n'
    const blob = new Blob([patched], { type: 'text/plain' })
    const form = new FormData()
    form.append('file', blob, 'printer.cfg')
    form.append('root', 'config')

    const uploadRes = await fetch('/server/files/upload', { method: 'POST', body: form })
    if (!uploadRes.ok) throw new Error(`Could not patch printer.cfg: ${uploadRes.status}`)
    return true
  } catch (e) {
    console.error('[bakesail] ensurePrinterCfgInclude failed:', e)
    return false
  }
}

// ── Internal naming helpers ───────────────────────────────────────────────────

function _zoneName(zone) {
  return zone.label
    ? zone.label.toLowerCase().replace(/\s+/g, '_')
    : `zone${zone.id}`
}

function _tcName(tc) {
  return tc.label
    ? tc.label.toLowerCase().replace(/\s+/g, '_')
    : `tc${tc.id}`
}

function _fanName(fan) {
  return fan.label
    ? fan.label.toLowerCase().replace(/\s+/g, '_')
    : `fan${fan.id}`
}

function _resolveHeaterPin(zone, settings) {
  if (!zone.deferred) return zone.pin || 'UNSET'
  // Find the stepper slot assigned to this zone
  const slotFunction = `heater_zone${zone.id}`
  const slot = settings.stepperSlots.find(s => s.function === slotFunction)
  return slot?.heaterPin || 'UNSET'
}

function _firstAvailablePin(settings) {
  const GPIO_POOL = [
    'gpio17','gpio18','gpio19','gpio20','gpio21',
    'gpio22','gpio23','gpio24','gpio25','gpio26','gpio27'
  ]
  const used = new Set()
  for (const z of (settings.zones || [])) if (z.pin) used.add(z.pin)
  for (const f of (settings.fans  || [])) if (f.pin) used.add(f.pin)
  if (settings.vacuum?.penPin)            used.add(settings.vacuum.penPin)
  if (settings.vacuum?.nozzlePin)         used.add(settings.vacuum.nozzlePin)
  if (settings.illumination?.laserPin)    used.add(settings.illumination.laserPin)
  if (settings.illumination?.neopixelPin) used.add(settings.illumination.neopixelPin)
  return GPIO_POOL.find(p => !used.has(p)) || 'gpio27'
}
